---
# --- Weblate client ---
- name: Install weblate client from pip
  pip:
    name: wlc==1.15
    state: present
    executable: pip3

# --- Weblate config (wlc) ---
- name: Ensure wlc config directory exists
  file:
    path: "{{ weblate_config_path | dirname }}"
    state: directory
    mode: "0700"

- name: Write wlc config file
  template:
    src: weblate.ini.j2
    dest: "{{ weblate_config_path }}"
    mode: "0600"
  no_log: true

# --- Weblate API curl config ---
- name: Write curlrc for Weblate API authentication
  copy:
    dest: "{{ ansible_user_dir }}/.curlrc"
    content: |
      header = "Authorization: Token {{ weblate_api_credentials.token }}"
    mode: "0600"
  no_log: true
