- name: Upstream Translation Updates
  hosts: localhost
  connection: local
  roles:
    - prepare-weblate-client

  tasks:
    - name: Run upstream_translation_update_weblate.sh script
      command: "{{ ansible_user_dir }}/scripts/upstream_translation_update_weblate.sh {{ zuul.project.short_name }} {{ zuul.job }} {{ zuul.branch }} {{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/horizon'].src_dir }}"
      args:
        chdir: "{{ zuul.project.src_dir }}"
