- name: Propose Translation Updates
  hosts: all
  tasks:
    - name: Run propose_translation_update_weblate.sh script
      shell: "{{ ansible_user_dir }}/scripts/propose_translation_update_weblate.sh {{ zuul.project.short_name }} {{ zuul.branch }} {{ zuul.job }}"
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      environment:
        WEBLATE_URL: "{{ weblate_api_credentials.url }}"
        WEBLATE_TOKEN: "{{ weblate_api_credentials.token }}"
        GITHUB_TOKEN: "{{ github_credentials.token }}"
        GITHUB_PROJECT: "{{ zuul.project.name }}"
